export const FRIEND_REQUEST = "FRIEND_REQUEST";
export const FRIEND_SUCCESS = "FRIEND_SUCCESS";
export const FRIEND_FAILED  = "FRIEND_FAILED";


export const FRIEND_LIST_REQUEST = "FRIEND_LIST_REQUEST";
export const FRIEND_LIST_SUCCESS = "FRIEND_LIST_SUCCESS";
export const FRIEND_LIST_FAILED  = "FRIEND_LIST_FAILED";

export const FRIEND_PENDING_REQUEST = "FRIEND_PENDING_REQUEST";
export const FRIEND_PENDING_SUCCESS = "FRIEND_PENDING_SUCCESS";
export const FRIEND_PENDING_FAILED  = "FRIEND_PENDING_FAILED";

export const FRIEND_ACCEPT_REQUEST = "FRIEND_ACCEPT_REQUEST";
export const FRIEND_ACCEPT_SUCCESS = "FRIEND_ACCEPT_SUCCESS";
export const FRIEND_ACCEPT_FAILED  = "FRIEND_ACCEPT_FAILED";

export const FRIEND_STATUS_REQUEST = "FRIEND_STATUS_REQUEST";
export const FRIEND_STATUS_SUCCESS = "FRIEND_STATUS_SUCCESS";
export const FRIEND_STATUS_FAILED  = "FRIEND_STATUS_FAILED";

export const FRIEND_UNFRIEND_REQUEST = "FRIEND_UNFRIEND_REQUEST";
export const FRIEND_UNFRIEND_SUCCESS = "FRIEND_UNFRIEND_SUCCESS";
export const FRIEND_UNFRIEND_FAILED  = "FRIEND_UNFRIEND_FAILED";
