export const CHAT_HISTORY_REQUEST = "CHAT_HISTORY_REQUEST";
export const CHAT_HISTORY_SUCCESS = "CHAT_HISTORY_SUCCESS";
export const CHAT_HISTORY_FAILED  = "CHAT_HISTORY_FAILED";


export const CHAT_LIST_REQUEST = "CHAT_LIST_REQUEST";
export const CHAT_LIST_SUCCESS = "CHAT_LIST_SUCCESS";
export const CHAT_LIST_FAILED  = "CHAT_LIST_FAILED";

export const CHAT_MARK_READ_REQUEST = "CHAT_MARK_READ_REQUEST";
export const CHAT_MARK_READ_SUCCESS = "CHAT_MARK_READ_SUCCESS";
export const CHAT_MARK_READ_FAILED  = "CHAT_MARK_READ_FAILED";

export const CHAT_FILE_UPLOAD_REQUEST = "CHAT_FILE_UPLOAD_REQUEST";
export const CHAT_FILE_UPLOAD_SUCCESS = "CHAT_FILE_UPLOAD_SUCCESS";
export const CHAT_FILE_UPLOAD_FAILED  = "CHAT_FILE_UPLOAD_FAILED";

export const CHAT_MESSAGE_ADD = "CHAT_MESSAGE_ADD";

export const CHAT_CLEAR = "CHAT_CLEAR";

export const CHAT_UNREAD_CLEAR = "CHAT_UNREAD_CLEAR";

export const CHAT_SET_ACTIVE = "CHAT_SET_ACTIVE";
export const CHAT_CLEAR_ACTIVE = "CHAT_CLEAR_ACTIVE";

export const CHAT_UNREAD_INCREASE = "CHAT_UNREAD_INCREASE";
export const CHAT_MESSAGE_DELIVERED = "CHAT_MESSAGE_DELIVERED";