export const USER_REGISTER_FETCH_REQUEST = "USER_REGISTER_FETCH_REQUEST";
export const USER_REGISTER_FETCH_SUCCESS = "USER_REGISTER_FETCH_SUCCESS";
export const USER_REGISTER_FETCH_FAILED = "USER_REGISTER_FETCH_FAILED";

export const USER_LOGIN_FETCH_REQUEST = "USER_LOGIN_FETCH_REQUEST";
export const USER_LOGIN_FETCH_SUCCESS = "USER_LOGIN_FETCH_SUCCESS";
export const USER_LOGIN_FETCH_FAILED = "USER_LOGIN_FETCH_FAILED";

export const USER_OTP_FETCH_REQUEST = "USER_OTP_FETCH_REQUES";
export const USER_OTP_FETCH_SUCCESS = "USER_OTP_FETCH_SUCCESS";
export const USER_OTP_FETCH_FAILED = "USER_OTP_FETCH_FAILED";
