export const CREATE_STATUS_REQUEST = "CREATE_STATUS_REQUEST";
export const CREATE_STATUS_SUCCESS = "CREATE_STATUS_SUCCESS";
export const CREATE_STATUS_FAILURE = "CREATE_STATUS_FAILURE";

/* 🔥 NEW FOR GET */

export const GET_MY_STATUS_REQUEST = "GET_MY_STATUS_REQUEST";
export const GET_MY_STATUS_SUCCESS = "GET_MY_STATUS_SUCCESS";
export const GET_MY_STATUS_FAILURE = "GET_MY_STATUS_FAILURE";

export const DELETE_STATUS_REQUEST = "DELETE_STATUS_REQUEST";
export const DELETE_STATUS_SUCCESS = "DELETE_STATUS_SUCCESS";
export const DELETE_STATUS_FAILURE = "DELETE_STATUS_FAILURE";
// 🔥 FRIEND STATUS
export const GET_FRIEND_STATUS_REQUEST = "GET_FRIEND_STATUS_REQUEST";
export const GET_FRIEND_STATUS_SUCCESS = "GET_FRIEND_STATUS_SUCCESS";
export const GET_FRIEND_STATUS_FAILURE = "GET_FRIEND_STATUS_FAILURE";

export const VIEW_STATUS_REQUEST = "VIEW_STATUS_REQUEST";


export const GET_VIEWERS_REQUEST = "GET_VIEWERS_REQUEST";
export const GET_VIEWERS_SUCCESS = "GET_VIEWERS_SUCCESS";
export const GET_VIEWERS_FAILURE = "GET_VIEWERS_FAILURE";