export const CREATE_WITHDRAW_REQUEST = "CREATE_WITHDRAW_REQUEST";
export const CREATE_WITHDRAW_SUCCESS = "CREATE_WITHDRAW_SUCCESS";
export const CREATE_WITHDRAW_FAILURE = "CREATE_WITHDRAW_FAILURE";

export const GET_WITHDRAW_HISTORY_REQUEST = "GET_WITHDRAW_HISTORY_REQUEST";
export const GET_WITHDRAW_HISTORY_SUCCESS = "GET_WITHDRAW_HISTORY_SUCCESS";
export const GET_WITHDRAW_HISTORY_FAILURE = "GET_WITHDRAW_HISTORY_FAILURE";

export const WITHDRAW_RESET = "WITHDRAW_RESET";