export const CALL_REQUEST = "CALL_REQUEST";
export const CALL_SUCCESS = "CALL_SUCCESS";
export const CALL_FAILED  = "CALL_FAILED";

export const FEMALE_SEARCH_REQUEST = "FEMALE_SEARCH_REQUEST";
export const FEMALE_SEARCH_SUCCESS = "FEMALE_SEARCH_SUCCESS";
export const FEMALE_SEARCH_FAILED  = "FEMALE_SEARCH_FAILED";

export const FEMALE_CANCEL_REQUEST = "FEMALE_CANCEL_REQUEST";
export const FEMALE_CANCEL_SUCCESS = "FEMALE_CANCEL_SUCCESS";
export const FEMALE_CANCEL_FAILED  = "FEMALE_CANCEL_FAILED";

export const SEARCHING_FEMALES_REQUEST = "SEARCHING_FEMALES_REQUEST";
export const SEARCHING_FEMALES_SUCCESS = "SEARCHING_FEMALES_SUCCESS";
export const SEARCHING_FEMALES_FAILED  = "SEARCHING_FEMALES_FAILED";

export const CALL_DETAILS_REQUEST = "CALL_DETAILS_REQUEST";
export const CALL_DETAILS_SUCCESS = "CALL_DETAILS_SUCCESS";
export const CALL_DETAILS_FAILED  = "CALL_DETAILS_FAILED";

export const DIRECT_CALL_REQUEST = "DIRECT_CALL_REQUEST";
export const DIRECT_CALL_SUCCESS = "DIRECT_CALL_SUCCESS";
export const DIRECT_CALL_FAILED  = "DIRECT_CALL_FAILED";


export const INCOMING_CALL_CONNECTED = "INCOMING_CALL_CONNECTED";

export const CLEAR_CALL="CLEAR_CALL";

export const FRIEND_CALL_REQUEST = "FRIEND_CALL_REQUEST";
export const FRIEND_CALL_SUCCESS = "FRIEND_CALL_SUCCESS";
export const FRIEND_CALL_FAILED  = "FRIEND_CALL_FAILED";

export const INCOMING_CALL_RINGING = "INCOMING_CALL_RINGING";
export const INCOMING_CALL_ACCEPT = "INCOMING_CALL_ACCEPT";
export const INCOMING_CALL_REJECT = "INCOMING_CALL_REJECT";

export const RECENT_CALL_REQUEST = "RECENT_CALL_REQUEST";
export const RECENT_CALL_SUCCESS = "RECENT_CALL_SUCCESS";
export const RECENT_CALL_FAILED  = "RECENT_CALL_FAILED";

export const CANCEL_WAITING_REQUEST = "CANCEL_WAITING_REQUEST";
export const CANCEL_WAITING_SUCCESS = "CANCEL_WAITING_SUCCESS";
export const CANCEL_WAITING_FAILED  = "CANCEL_WAITING_FAILED";