export const CALL_REQUEST = "CALL_REQUEST";
export const CALL_SUCCESS = "CALL_SUCCESS";
export const CALL_FAILED  = "CALL_FAILED";
export const CALL_RESET   = "CALL_RESET";

export const RECENT_CALL_REQUEST = "RECENT_CALL_REQUEST";
export const RECENT_CALL_SUCCESS = "RECENT_CALL_SUCCESS";
export const RECENT_CALL_FAILED  = "RECENT_CALL_FAILED";
export const RECENT_CALL_RESET   = "RECENT_CALL_RESET";
