export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_FAILED = "USER_EDIT_FAILED";

export const USER_DATA_REQUEST = "USER_DATA_REQUEST";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_FAILED = "USER_DATA_FAILED";
export const USER_LOGOUT_REQUEST="USER_LOGOUT_REQUEST";


export const NEW_USER_DATA_REQUEST = "NEW_USER_DATA_REQUEST";
export const NEW_USER_DATA_SUCCESS = "NEW_USER_DATA_SUCCESS";
export const NEW_USER_DATA_FAILED = "NEW_USER_DATA_FAILED";

export const USER_DATA_SILENT_REQUEST = 'USER_DATA_SILENT_REQUEST';

export const RESET_USER_STATE = 'RESET_USER_STATE';